#!/usr/bin/env bash
# ============================================================================
# auto-implement-and-pr.sh — v6.0 (native dispatch, per-agent PR)
#
# Each agent: create branch -> develop -> commit -> push -> create PR.
# Orchestrator: pre-compute DAG, dispatch ready phases, let Claude Code's
# native <task-notification> trigger the next turn. Newly-ready phases
# auto-launch alongside still-running ones.
#
# USAGE: cat auto-implement-and-pr.sh | claude
# ============================================================================

IMPL_PLAN_DIR="d:/ewm robot/reference/design all/implementation plan"
PROJECT_ROOT="D:/EWM ROBOT/ROBOTIC PLATFORM CODES"
TODAY_DATE=$(date +%Y%m%d 2>/dev/null || echo 'TODAY')
PLAN_FILE=$(ls -t "${IMPL_PLAN_DIR}"/*${TODAY_DATE}*.* 2>/dev/null | head -1)
[ -z "${PLAN_FILE}" ] && echo "ERROR: No plan found for ${TODAY_DATE}" && exit 1

echo "=== auto-implement-and-pr v6.0 (per-agent PR) ==="
echo "Plan: ${PLAN_FILE}"
echo ""

# ═══════════════════════════════════════════════════════════════
# PHASE 0 — SETUP
# ═══════════════════════════════════════════════════════════════

echo "PHASE 0 — SETUP"
echo ""

echo "0.1 Ensure clean starting state:"
echo "    cd ${PROJECT_ROOT}"
echo "    git checkout main && git pull"
echo "    git status  # must be clean"
echo ""

echo "0.2 Read plan: ${PLAN_FILE}"
echo "    For each phase extract:"
echo "      id, priority(P0|P1), title, creates[], consumes[], files[], verify"
echo ""

echo "0.3 Pre-compute DAG:"
echo ""
echo "    Logical (creates -> consumes):"
echo "      creates_map[key] = [producers], consumes_map[key] = [consumers]"
echo "      for each match: consumer.logical_deps += producer"
echo ""
echo "    Mechanical (file overlap):"
echo "      file_map[path] = [phase_ids]"
echo "      >1 phase per file -> conflict -> must sequence"
echo "      Order: P0 before P1, then by ID"
echo ""

echo "0.4 Create native Task items:"
echo "    for each phase:"
echo "      TaskCreate("
echo "        subject: \"[P0|P1] <id>: <title>\""
echo "        metadata: {"
echo "          phase_id, priority, title, files,"
echo "          logical_deps, verify"
echo "        }"
echo "      )"
echo ""

# ═══════════════════════════════════════════════════════════════
# DISPATCH LOOP
# ═══════════════════════════════════════════════════════════════

echo "=== DISPATCH LOOP ==="
echo ""

echo "READY CHECK (every turn):"
echo ""
echo "  def ready(phase):"
echo "    # A: all logical deps completed (their PRs merged or branches exist)"
echo "    if any(dep.status != 'completed' for dep in phase.logical_deps):"
echo "      return False"
echo "    # B: no file overlap with any RUNNING phase"
echo "    running = [p for p in all if p.status == 'in_progress']"
echo "    if any(overlap(phase.files, r.files) for r in running):"
echo "      return False"
echo "    return True"
echo ""

echo "----------------------------------------------------------------"
echo "TURN 0 — INITIAL DISPATCH"
echo "----------------------------------------------------------------"
echo ""
echo "1. Find all phases where ready() == true"
echo "2. Resolve mutual file conflicts among ready phases:"
echo "   if two ready phases share files -> only dispatch one (P0 first, then ID)"
echo "3. Dispatch each with Agent(run_in_background=true):"
echo ""
echo "   for phase in to_dispatch:"
echo "     TaskUpdate(task_id, status='in_progress')"
echo "     Agent("
echo "       subagent_type: \"general-purpose\""
echo "       description: \"<id> [P0|P1]: <title>\""
echo "       run_in_background: true"
echo "       prompt: AGENT_WORKFLOW(phase)"
echo "     )"
echo ""
echo "4. END TURN"
echo ""

echo "----------------------------------------------------------------"
echo "TURN 1+ — AUTO-CONTINUE (triggered by <task-notification>)"
echo "----------------------------------------------------------------"
echo ""
echo "A. CHECK COMPLETIONS:"
echo "   for phase in in_progress:"
echo "     result = TaskOutput(phase.agent_task_id, block=false)"
echo "     if result.done and success:"
echo "       TaskUpdate(task_id, status='completed')"
echo "       record: phase.branch, phase.pr_url (from agent output)"
echo "     elif result.done and failed:"
echo "       TaskUpdate(task_id, status='failed')"
echo "       for dep in get_logical_dependents(phase):"
echo "         TaskUpdate(dep.task_id, status='skipped')"
echo ""
echo "B. CHECK DONE:"
echo "   pending_or_running = TaskList(pending | in_progress)"
echo "   if 0: -> REPORT RESULTS + STOP"
echo ""
echo "C. DISPATCH NEWLY READY:"
echo "   ready_phases = [p for p in pending if ready(p)]"
echo "   resolve mutual file conflicts (same as Turn 0)"
echo "   dispatch with Agent(run_in_background=true), TaskUpdate -> in_progress"
echo ""
echo "D. END TURN:"
echo "   if dispatched > 0:"
echo "     -> END TURN (wait for next <task-notification>)"
echo "   elif in_progress > 0:"
echo "     -> Report '<N> running, <M> pending, waiting...' END TURN"
echo "   else:"
echo "     -> REPORT RESULTS + STOP"
echo ""

echo "----------------------------------------------------------------"
echo "EXAMPLE (8 phases)"
echo "----------------------------------------------------------------"
echo ""
echo "Turn 0: fire P0-1 + P1-4 + P1-7 + P1-8"
echo "  P0-1: branch feat/p0-1-cold-start -> dev -> commit -> push -> PR#1"
echo "  P1-4: branch feat/p1-4-playback-api -> dev -> commit -> push -> PR#4"
echo "  P1-7: branch feat/p1-7-grafana -> dev -> commit -> push -> PR#7"
echo "  P1-8: branch feat/p1-8-scenario -> dev -> commit -> push -> PR#8"
echo ""
echo "<notification: P1-7 done> Turn 1: P1-7(PR#7)✓. Nothing new ready."
echo "<notification: P1-8 done> Turn 2: P1-8(PR#8)✓. Nothing new ready."
echo "<notification: P0-1 done> Turn 3: P0-1(PR#1)✓. P0-3 ready (no overlap w/ P1-4). Fire P0-3."
echo "  P0-3: branch feat/p0-3-worm-disk -> dev -> commit -> push -> PR#3"
echo "<notification: P1-4 done> Turn 4: P1-4(PR#4)✓. P0-2,P1-6 ready. P0-2∩P0-3(running)files=config.py! Defer P0-2. Fire P1-6."
echo "  P1-6: branch feat/p1-6-dashboard -> dev -> commit -> push -> PR#6"
echo "...continues until all 8 phases done, each with own branch + PR..."
echo ""

# ═══════════════════════════════════════════════════════════════
# AGENT WORKFLOW (what each agent does)
# ═══════════════════════════════════════════════════════════════

echo "==========================================================="
echo "  AGENT WORKFLOW (per-phase, self-contained)"
echo "==========================================================="
echo ""
echo "Each agent executes this FULL workflow independently:"
echo ""
echo "  subagent_type: \"general-purpose\""
echo "  description: \"<id> [P0|P1]: <title>\""
echo "  run_in_background: true"
echo ""
echo "  prompt:"
echo ""
echo "    You are implementing ONE phase from the plan at: ${PLAN_FILE}"
echo "    Project root: ${PROJECT_ROOT}"
echo "    Your phase: <id> [Priority: P0|P1]: <title>"
echo ""
echo "    ┌──────────────────────────────────────────────────────┐"
echo "    │ STEP 1: CREATE BRANCH                                │"
echo "    │                                                      │"
echo "    │ cd ${PROJECT_ROOT}                                   │"
echo "    │ git checkout main && git pull                        │"
echo "    │ # If your phase has logical deps, their branches     │"
echo "    │ # have been merged to main. Pull gets their code.    │"
echo "    │ BRANCH=\"feat/<phase-id>-<slug>\"                      │"
echo "    │ git checkout -b $BRANCH                              │"
echo "    └──────────────────────────────────────────────────────┘"
echo ""
echo "    ┌──────────────────────────────────────────────────────┐"
echo "    │ STEP 2: DEVELOP                                       │"
echo "    │                                                      │"
echo "    │ a. Read your phase section from the plan              │"
echo "    │ b. Read EVERY file listed in **Files:** BEFORE editing│"
echo "    │ c. Make ALL changes in **Changes:**                   │"
echo "    │    Match existing code style, comments, naming        │"
echo "    │ d. Run: <verify command>                              │"
echo "    │    If fails, fix and re-run until green               │"
echo "    └──────────────────────────────────────────────────────┘"
echo ""
echo "    ┌──────────────────────────────────────────────────────┐"
echo "    │ STEP 3: COMMIT & PUSH                                 │"
echo "    │                                                      │"
echo "    │ git add .                                            │"
echo "    │ git commit -m \"feat(<id>): <title>                    │"
echo "    │                                                  │"
echo "    │ Co-Authored-By: Claude Code <noreply@anthropic.com>\" │"
echo "    │ git push -u origin $BRANCH                           │"
echo "    └──────────────────────────────────────────────────────┘"
echo ""
echo "    ┌──────────────────────────────────────────────────────┐"
echo "    │ STEP 4: CREATE PR                                     │"
echo "    │                                                      │"
echo "    │ gh pr create \\                                       │"
echo "    │   --title \"feat(<id>): <title>\" \\                    │"
echo "    │   --body \"Phase: <id> [P0|P1]                         │"
echo "    │ Plan: ${PLAN_FILE}                                    │"
echo "    │ Priority: <P0|P1>                                    │"
echo "    │ Files changed:                                        │"
echo "    │ - <file>                                              │"
echo "    │ ...                                                   │"
echo "    │                                                       │"
echo "    │ Generated with Claude Code auto-implement v6.0\"      │"
echo "    └──────────────────────────────────────────────────────┘"
echo ""
echo "    ┌──────────────────────────────────────────────────────┐"
echo "    │ STEP 5: REPORT                                        │"
echo "    │                                                      │"
echo "    │ Return EXACTLY this format:                           │"
echo "    │   STATUS: SUCCESS | FAILURE                          │"
echo "    │   BRANCH: <branch-name>                              │"
echo "    │   PR: <pr-url>                                       │"
echo "    │   FILES:                                             │"
echo "    │     - <absolute-path>                                │"
echo "    │   OUTPUT: <verify command output>                    │"
echo "    └──────────────────────────────────────────────────────┘"
echo ""

echo "==========================================================="
echo "  FINAL REPORT"
echo "==========================================================="
echo ""
echo "When all phases complete (none pending, none in_progress):"
echo ""
echo "  TaskList shows every phase: completed | failed | skipped"
echo ""
echo "  Print summary:"
echo "    Phase     | Status    | Priority | Branch          | PR"
echo "    ----------|-----------|----------|-----------------|-----"
echo "    P0-1: ... | completed | P0       | feat/p0-1-...  | #1"
echo "    P0-2: ... | completed | P0       | feat/p0-2-...  | #2"
echo "    ..."
echo ""
echo "  Overall PR decision:"
echo "    Any P0 failed? -> mark as BLOCKED, do not merge"
echo "    Otherwise -> all PRs ready for review"
echo ""

echo "=== auto-implement-and-pr v6.0 END ==="
