#!/usr/bin/env bash
# ============================================================================
# auto-plan-implement-and-pr.sh — v6.0 (native dispatch, per-agent PR)
#
# Reads design docs, generates plan, then auto-dispatches. Each agent does
# its own: create branch -> develop -> commit -> push -> create PR.
# Claude Code's native <task-notification> triggers each new turn.
#
# USAGE: cat auto-plan-implement-and-pr.sh | claude
# ============================================================================

EXTERNAL_DESIGN_DIR="d:/ewm robot/reference/design all"
IMPL_PLAN_DIR="${EXTERNAL_DESIGN_DIR}/implementation plan"
PROJECT_ROOT="D:/EWM ROBOT/ROBOTIC PLATFORM CODES"
TODAY_DATE=$(date +%Y%m%d 2>/dev/null || echo 'TODAY')
PLAN_FILE=$(ls -t "${IMPL_PLAN_DIR}"/*${TODAY_DATE}*.* 2>/dev/null | head -1)
[ -z "${PLAN_FILE}" ] && PLAN_FILE="${IMPL_PLAN_DIR}/IMPLEMENTATION_PLAN_${TODAY_DATE}.md"

echo "=== auto-plan-implement-and-pr v6.0 (per-agent PR) ==="
echo "Design: ${EXTERNAL_DESIGN_DIR}"
echo "Plan:   ${PLAN_FILE}"
echo ""

# ═══════════════════════════════════════════════════════════════
# STAGE 1 — GENERATE PLAN
# ═══════════════════════════════════════════════════════════════

echo "=== STAGE 1: GENERATE PLAN ==="
echo ""

echo "1.1 Read design docs:"
echo "    Glob + Read all .md in:"
echo "      ${IMPL_PLAN_DIR}/"
echo "      ${EXTERNAL_DESIGN_DIR}/Design - Core/"
echo "    Key: 异构机器人融合平台_v5.0_完整堡垒版.md, 01_架构白皮书, 02_Function_Spec, 03_Runbook"
echo ""

echo "1.2 Explore codebase:"
echo "    Glob ${PROJECT_ROOT}"
echo "    Read: core/config.py, core/coordinator.py, core/gateway.py,"
echo "    core/survival/worm_blackbox.py, core/survival/version_router.py,"
echo "    traffic_coordinator_v5/traffic_coordinator_main.py,"
echo "    traffic_coordinator_v5/simulator/cli.py, fleet.py,"
echo "    docker-compose-v5.yml, dashboard/src/, monitoring/"
echo ""

echo "1.3 Derive phases (dynamic count, not fixed):"
echo "    For each candidate, determine CREATES, CONSUMES, FILES."
echo "    Phases sharing files CANNOT run in parallel."
echo "    High file contention -> split or merge phases."
echo ""

echo "1.4 Write plan to ${PLAN_FILE}:"
echo ""
echo "    ## 1. CURRENT BASELINE"
echo ""
echo "    ## 2. IMPLEMENTATION PHASES"
echo "      For each phase:"
echo ""
echo "      ### <Phase ID>: <Title>"
echo "      **Priority:** P0 | P1"
echo "        P0 = critical (blocks PR on failure, wins tie-break)"
echo "        P1 = normal   (noted in PR on failure, loses tie-break)"
echo "      **Creates:**"
echo "        - \`func()\` in \`module.py\` — new method"
echo "        - \`GET /api/x\` in \`main.py\` — new endpoint"
echo "        - \`Class.field\` in \`config.py\` — new config"
echo "      **Consumes:**"
echo "        - \`existing_func()\` from \`module.py\`"
echo "        - \`GET /api/existing\`"
echo "      **Files:**"
echo "        - \`path/to/file\` — what to change"
echo "        EVERY file touched. Determines mechanical constraints."
echo "      **Changes:**"
echo "        - Specific implementation details"
echo "      **Verify:** \`exact command\`"
echo ""
echo "      *** NO Depends on: field. Dependencies are auto-detected. ***"
echo ""
echo "    ## 3. CREATES/CONSUMES CROSS-REFERENCE"
echo "    ## 4. FILE CONTENTION MAP"
echo "    ## 5. VERIFICATION CRITERIA"
echo "    ## 6. FILE CHANGE MATRIX"
echo "    ## 7. OUT OF SCOPE"
echo ""

# ═══════════════════════════════════════════════════════════════
# STAGE 1.5 — DAG SETUP
# ═══════════════════════════════════════════════════════════════

echo "=== STAGE 1.5: DAG SETUP ==="
echo ""

echo "1.5a Ensure clean starting state:"
echo "     cd ${PROJECT_ROOT}"
echo "     git checkout main && git pull"
echo "     git status  # must be clean"
echo ""

echo "1.5b Pre-compute DAG from plan:"
echo ""
echo "     Logical (creates -> consumes):"
echo "       creates_map[key] = [producers]"
echo "       consumes_map[key] = [consumers]"
echo "       for each match: consumer.logical_deps += producer"
echo ""
echo "     Mechanical (file overlap):"
echo "       file_map[path] = [phase_ids]"
echo "       >1 phase per file -> conflict -> sequence"
echo ""
echo "     Each agent branches from main (which gets updated as"
echo "     prior phases merge). Logical deps assumed satisfied"
echo "     once the dep phase is 'completed' (its PR exists)."
echo ""

echo "1.5c Create native Task items:"
echo "     for each phase:"
echo "       TaskCreate("
echo "         subject: \"[P0|P1] <id>: <title>\""
echo "         metadata: { phase_id, priority, title, files,"
echo "                     logical_deps, verify }"
echo "       )"
echo ""

# ═══════════════════════════════════════════════════════════════
# STAGE 2 — AUTO-DISPATCH LOOP
# ═══════════════════════════════════════════════════════════════

echo "=== STAGE 2: AUTO-DISPATCH LOOP ==="
echo ""

echo "READY CHECK (reused every turn):"
echo ""
echo "  def ready(phase):"
echo "    # A: all logical deps completed (their PRs exist)"
echo "    if any(dep.status != 'completed' for dep in phase.logical_deps):"
echo "      return False"
echo "    # B: no file overlap with any RUNNING phase"
echo "    running = [p for p in all if p.status == 'in_progress']"
echo "    if any(overlap(phase.files, r.files) for r in running):"
echo "      return False"
echo "    return True"
echo ""

echo "----------------------------------------------------------------"
echo "TURN 0 — INITIAL DISPATCH"
echo "----------------------------------------------------------------"
echo ""
echo "1. Find all phases where ready() == true"
echo "2. Resolve mutual file conflicts:"
echo "   two ready phases sharing files -> dispatch only one"
echo "   (P0 > P1, then lower ID)"
echo "3. Dispatch:"
echo ""
echo "   for phase in to_dispatch:"
echo "     TaskUpdate(task_id, status='in_progress')"
echo "     Agent("
echo "       subagent_type: \"general-purpose\""
echo "       description: \"<id> [P0|P1]: <title>\""
echo "       run_in_background: true"
echo "       prompt: AGENT_WORKFLOW  # see STAGE 2 appendix"
echo "     )"
echo "     store agent_task_id"
echo ""
echo "4. END TURN. Wait for native <task-notification>."
echo ""

echo "----------------------------------------------------------------"
echo "TURN 1+ — AUTO-CONTINUE"
echo "----------------------------------------------------------------"
echo ""
echo "A. CHECK COMPLETIONS:"
echo "   for each in_progress phase:"
echo "     result = TaskOutput(agent_task_id, block=false)"
echo "     if done + success:"
echo "       TaskUpdate(task_id, status='completed')"
echo "       record branch, pr_url from agent output"
echo "     if done + failure:"
echo "       TaskUpdate(task_id, status='failed')"
echo "       for dep in logical_dependents_of(phase):"
echo "         TaskUpdate(dep.task_id, status='skipped')"
echo ""
echo "B. CHECK DONE:"
echo "   pending_or_running = TaskList filter (pending | in_progress)"
echo "   if count == 0: -> REPORT & STOP"
echo ""
echo "C. DISPATCH NEWLY READY:"
echo "   ready_phases = [p for p in pending if ready(p)]"
echo "   resolve mutual file conflicts"
echo "   dispatch with Agent(run_in_background=true)"
echo "   TaskUpdate -> 'in_progress'"
echo ""
echo "D. END TURN:"
echo "   dispatched > 0: end turn, wait for notification"
echo "   in_progress > 0, dispatched == 0: report waiting, end turn"
echo "   neither: -> REPORT & STOP"
echo ""

echo "----------------------------------------------------------------"
echo "EXAMPLE (8 phases)"
echo "----------------------------------------------------------------"
echo ""
echo "Turn 0: fire P0-1 + P1-4 + P1-7 + P1-8 (bg)"
echo "  Each creates own branch, develops, commits, pushes, creates PR"
echo ""
echo "<notification: P1-7 done>  Turn 1: P1-7✓. No new ready."
echo "<notification: P1-8 done>  Turn 2: P1-8✓. No new ready."
echo "<notification: P0-1 done>  Turn 3: P0-1✓. P0-3 ready. Fire P0-3."
echo "<notification: P1-4 done>  Turn 4: P1-4✓. P1-6 ready. P0-2∩P0-3(running)=config.py! Defer P0-2. Fire P1-6."
echo "<notification: P0-3 done>  Turn 5: P0-3✓. P0-2 ready. P1-5∩P0-2=config.py! Defer P1-5. Fire P0-2."
echo "<notification: P1-6 done>  Turn 6: P1-6✓. P0-2 running. P1-5 not ready (config.py w/ P0-2)."
echo "<notification: P0-2 done>  Turn 7: P0-2✓. P1-5 ready. Fire P1-5."
echo "<notification: P1-5 done>  Turn 8: ALL DONE."
echo ""
echo "Result: 8 branches, 8 PRs, independently reviewable."
echo ""

# ═══════════════════════════════════════════════════════════════
# AGENT WORKFLOW
# ═══════════════════════════════════════════════════════════════

echo "==========================================================="
echo "  AGENT WORKFLOW (each phase runs this independently)"
echo "==========================================================="
echo ""
echo "subagent_type: \"general-purpose\""
echo "description: \"<id> [P0|P1]: <title>\""
echo "run_in_background: true"
echo ""
echo "prompt:"
echo ""
echo "  You are implementing ONE phase from: ${PLAN_FILE}"
echo "  Project root: ${PROJECT_ROOT}"
echo "  Your phase: <id> [Priority: P0|P1]: <title>"
echo ""
echo "  STEP 1 — CREATE BRANCH:"
echo "    cd ${PROJECT_ROOT}"
echo "    git checkout main && git pull"
echo "    # Prior phases' PRs should be merged by now, so main has their code."
echo "    BRANCH=\"feat/<phase-id>-<short-slug>\""
echo "    git checkout -b $BRANCH"
echo ""
echo "  STEP 2 — DEVELOP:"
echo "    a. Read your phase section from the plan"
echo "    b. Read EVERY file listed in **Files:** BEFORE editing"
echo "    c. Make ALL changes in **Changes:**"
echo "       Match existing code style, comments, naming"
echo "    d. Run: <verify command>"
echo "       If fails, fix and re-run until green"
echo ""
echo "  STEP 3 — COMMIT & PUSH:"
echo "    git add ."
echo "    git commit -m \"feat(<id>): <title>"
echo ""
echo "    Co-Authored-By: Claude Code <noreply@anthropic.com>\""
echo "    git push -u origin $BRANCH"
echo ""
echo "  STEP 4 — CREATE PR:"
echo "    gh pr create \\"
echo "      --title \"feat(<id>): <title>\" \\"
echo "      --body \"Phase: <id> [P0|P1]"
echo "    Plan: ${PLAN_FILE}"
echo "    Priority: <P0|P1>"
echo "    Files changed:"
echo "    - <file>"
echo "    ..."
echo ""
echo "    Generated with Claude Code auto-implement v6.0\""
echo ""
echo "  STEP 5 — REPORT (exact format):"
echo "    STATUS: SUCCESS | FAILURE"
echo "    BRANCH: <branch-name>"
echo "    PR: <pr-url>"
echo "    FILES:"
echo "      - <absolute-path>"
echo "    OUTPUT: <verify output>"
echo ""

# ═══════════════════════════════════════════════════════════════
# FINAL REPORT
# ═══════════════════════════════════════════════════════════════

echo "==========================================================="
echo "  FINAL REPORT"
echo "==========================================================="
echo ""
echo "When TaskList shows no pending and no in_progress:"
echo ""
echo "  Phase     | Status    | Priority | Branch          | PR"
echo "  ----------|-----------|----------|-----------------|-----"
echo "  P0-1: ... | completed | P0       | feat/p0-1-...  | #1"
echo "  P0-2: ... | completed | P0       | feat/p0-2-...  | #2"
echo "  ..."
echo ""
echo "  Any P0 failed? -> BLOCKED. Do not merge."
echo "  All P0 pass?   -> All PRs ready for review."
echo ""

echo "=== auto-plan-implement-and-pr v6.0 END ==="
