#!/usr/bin/env bash
# ============================================================================
# auto-implement-and-pr.sh — v6.2 (chain-collapse, no incremental merge)
#
# Reads a pre-built plan. Pre-computes constraint DAG ONCE. Collapses
# logically-dependent phases into CHAINS (one agent, one branch, one PR).
# Dispatches chains via Claude Code native Agent(run_in_background=true).
# <task-notification> triggers each turn.

# USAGE: cat auto-implement-and-pr.sh | claude
# ============================================================================

IMPL_PLAN_DIR="d:/ewm robot/reference/design all/implementation plan"
PROJECT_ROOT="D:/EWM ROBOT/ROBOTIC PLATFORM CODES"
TODAY_DATE=$(date +%Y%m%d 2>/dev/null || echo 'TODAY')
PLAN_FILE=$(ls -t "${IMPL_PLAN_DIR}"/*${TODAY_DATE}*.* 2>/dev/null | head -1)
[ -z "${PLAN_FILE}" ] && echo "ERROR: No plan found for ${TODAY_DATE}" && exit 1
BRANCH="feat/auto-impl-$(date +%Y%m%d-%H%M%S 2>/dev/null || echo 'snapshot')"
MAX_RUNTAIME=1800  # 30 minutes per chain before timeout
SAFETY_WAKEUP=300 # 5 minutes — if no notification, wake up and check

echo "=== auto-implement-and-pr v6.2 (chain-collapse) ==="
echo "Plan:   ${PLAN_FILE}"
echo "Branch: ${BRANCH}"
echo ""

# ═══════════════════════════════════════════════════════════════
# PHASE 0 — SETUP + PRE-COMPUTE + COLLAPSE CHAINS
# ═══════════════════════════════════════════════════════════════

echo "PHASE 0 — SETUP"
echo ""

echo "0.1 Create shared integration branch:"
echo "    cd ${PROJECT_ROOT}"
echo "    git checkout main && git pull"
echo "    git checkout -b ${BRANCH}"
echo "    git push -u origin ${BRANCH}"
echo ""

echo "0.2 Read plan: ${PLAN_FILE}"
echo "    For each phase extract:"
echo "      id, priority(P0|P1), title, creates[], consumes[], files[], verify"
echo ""

echo "0.3 Pre-compute logical deps (creates -> consumes):"
echo ""
echo "    creates_map[\"module::func()\"] = [producers]"
echo "    consumes_map[\"module::func()\"] = [consumers]"
echo "    for each match where producer != consumer:"
echo "      consumer.logical_deps += producer"
echo ""

echo "0.4 COLLAPSE logical dependency chains into single units:"
echo ""
echo "    WHY: If B depends on A, B needs A's code to exist. Splitting"
echo "    them into separate agents requires waiting for A's PR to merge"
echo "    before B can start. COLLAPSING them into one chain eliminates"
echo "    the merge latency — one agent implements both in sequence,"
echo "    one branch, one PR."
echo ""
echo "    ALGORITHM:"
echo "      chains = []"
echo "      visited = set()"
echo "      for phase in topological_order:"
echo "        if phase in visited: continue"
echo "        chain = [phase]"
echo "        current = phase"
echo "        while current has exactly one dependent"
echo "              AND that dependent only depends on current:"
echo "          chain.append(dependent)"
echo "          current = dependent"
echo "        visited.add_all(chain)"
echo "        chains.append(chain)"
echo ""
echo "    Example (8-phase plan):"
echo "      Logical deps detected: P1-6 depends on P1-4 (consumes /playback)"
echo "      Chains:"
echo "        C1: [P0-1]              (independent)"
echo "        C2: [P0-2]              (independent)"
echo "        C3: [P0-3]              (independent)"
echo "        C4: [P1-4, P1-6]        (collapsed! one agent, one PR)"
echo "        C5: [P1-5]              (independent)"
echo "        C6: [P1-7]              (independent)"
echo "        C7: [P1-8]              (independent)"
echo "      8 phases -> 7 chains -> 7 agents -> 7 PRs"
echo ""

echo "0.5 Compute chain-level file conflicts:"
echo ""
echo "    chain_files[chain] = union of all files in chain"
echo "    For chains (i, j) where chain_files[i] ∩ chain_files[j] != ∅:"
echo "      chain_conflicts[i] += j"
echo "      chain_conflicts[j] += i"
echo ""

echo "0.6 Create native Task items (one per CHAIN, not per phase):"
echo ""
echo "    for chain in chains:"
echo "      TaskCreate("
echo "        subject: \"[<best-prio>] <chain-label>: <titles>\""
echo "        metadata: {"
echo "          chain_id, phases: [...], priority: max(phases),"
echo "          files: union of all phase files,"
echo "          chain_conflicts: [...],"
echo "          verify_all: [per-phase verify commands]"
echo "        }"
echo "      )"
echo ""

echo "0.7 ready() for chains:"
echo ""
echo "    def ready(chain):"
echo "      # Chains have no logical deps (already collapsed)"
echo "      # Only file conflicts with RUNNING chains matter"
echo "      for conflict in chain.chain_conflicts:"
echo "        if conflict in running:"
echo "          return False"
echo "      return True"
echo ""

# ═══════════════════════════════════════════════════════════════
# PHASE 1 — DISPATCH LOOP
# ═══════════════════════════════════════════════════════════════

echo "PHASE 1 — DISPATCH LOOP"
echo ""

echo "    TURN 0 — initial dispatch:"
echo ""
echo "      ready_chains = [c for c in chains if ready(c)]"
echo "      to_fire = resolve_mutual_file_conflicts(ready_chains)"
echo ""
echo "      for chain in to_fire:"
echo "        TaskUpdate(task_id, status='in_progress',"
echo "          metadata: { started_at: current_timestamp() })"
echo "        Agent("
echo "          subagent_type: \"general-purpose\""
echo "          description: \"<chain-id> [P0|P1]: <titles>\""
echo "          run_in_background: true"
echo "          prompt: CHAIN_AGENT_PROMPT(chain)"
echo "        )"
echo "      END TURN"
echo ""

echo "    TURN 1+ — triggered by <task-notification>:"
echo ""
echo "      # A. UPDATE STATUS"
echo "      for chain in in_progress:"
echo "        r = TaskOutput(chain.agent_task_id, block=false)"
echo "        if r.done and r.success:"
echo "          TaskUpdate(task_id, status='completed')"
echo "          # PR already created by agent. Merge immediately:"
echo "          gh pr merge feat/<chain-id>-<slug> --squash --delete-branch"
echo "          if merge_failed:"
echo "            TaskUpdate(task_id, status='merge_failed')"
echo "            # No dependents to skip — chain is self-contained"
echo "        elif r.done and not r.success:"
echo "          TaskUpdate(task_id, status='failed')"
echo "          gh pr close feat/<chain-id>-<slug> 2>/dev/null"
echo ""
echo "      # A2. TIMEOUT CHECK — hung agents"
echo "      now = current_timestamp()"
echo "      for chain in in_progress:"
echo "        elapsed = now - chain.started_at"
echo "        if elapsed > ${MAX_RUNTIME}:"
echo "          TaskStop(chain.agent_task_id)"
echo "          TaskUpdate(task_id, status='timeout',"
echo "            reason: \"exceeded ${MAX_RUNTIME}s (ran ${elapsed}s)\")"
echo "          gh pr close feat/<chain-id>-<slug> 2>/dev/null"
echo "          # No cascade — chains are independent"
echo ""
echo "      # B. CHECK DONE"
echo "      if no pending and no in_progress: -> GOTO PHASE 2"
echo ""
echo "      # C. DISPATCH NEWLY READY"
echo "      ready_chains = [c for c in pending if ready(c)]"
echo "      to_fire = resolve_mutual_file_conflicts(ready_chains)"
echo "      if to_fire:"
echo "        for chain in to_fire:"
echo "          TaskUpdate(task_id, status='in_progress',"
echo "            metadata: { started_at: current_timestamp() })"
echo "          Agent(subagent_type: \"general-purpose\","
echo "            description: \"<chain-id> [P0|P1]: <titles>\","
echo "            run_in_background: true,"
echo "            prompt: CHAIN_AGENT_PROMPT(chain))"
echo "        END TURN"
echo "      elif in_progress:"
echo "        Report: '<N> running, <M> pending. Timeout: ${MAX_RUNTIME}s per chain.'"
echo "        # Safety net: if no notification arrives, wake up and check"
echo "        ScheduleWakeup(delaySeconds=${SAFETY_WAKEUP},"
echo "          reason=\"hung-agent check: \${in_progress_count} chains running\")"
echo "        END TURN"
echo "      else: -> GOTO PHASE 2"
echo ""

# ═══════════════════════════════════════════════════════════════
# PHASE 2 — FINAL PR TO MAIN
# ═══════════════════════════════════════════════════════════════

echo "PHASE 2 — FINAL PR TO MAIN"
echo ""
echo "    cd ${PROJECT_ROOT}"
echo "    git checkout ${BRANCH} && git pull"
echo ""
echo "    if any(chain.priority == 'P0' and chain.status == 'failed'):"
echo "      -> STOP. P0 chain failed. Report and exit."
echo ""
echo "    gh pr create --base main --head ${BRANCH} \\"
echo "      --title \"feat: auto-implemented ($(date +%Y%m%d))\" \\"
echo "      --body \"Plan: ${PLAN_FILE} | ${N} chains, ${M} phases | v6.2\""
echo ""

# ═══════════════════════════════════════════════════════════════
# CHAIN AGENT PROMPT (single agent implements sequential phases)
# ═══════════════════════════════════════════════════════════════

echo "==========================================================="
echo "  CHAIN AGENT PROMPT"
echo "==========================================================="
echo ""
echo "    subagent_type: \"general-purpose\""
echo "    description: \"<chain-id> [<P0|P1>]: <titles>\""
echo "    run_in_background: true"
echo ""
echo "    prompt:"
echo "      Implement ${N} phases IN SEQUENCE from: ${PLAN_FILE}"
echo "      Project root: ${PROJECT_ROOT}"
echo "      Shared base: ${BRANCH}"
echo "      Your chain: <phase1> -> <phase2> -> ..."
echo ""
echo "      STEPS:"
echo "      1. git fetch origin"
echo "         git checkout -b feat/<chain-id>-<slug> origin/${BRANCH}"
echo ""
echo "      2. FOR EACH phase in chain (in dependency order):"
echo "         a. Read the phase section from the plan"
echo "         b. Read EVERY file listed in **Files:** BEFORE editing"
echo "         c. Make ALL changes in **Changes:**"
echo "            Match existing code style, comments, naming"
echo "         d. Run: <verify command>. Fix until green."
echo "         e. git add ."
echo "            git commit -m \"feat(<phase-id>): <title>"
echo ""
echo "            Co-Authored-By: Claude Code <noreply@anthropic.com>\""
echo "         f. If any phase FAILS: stop chain. Report FAILURE."
echo ""
echo "      3. git push -u origin feat/<chain-id>-<slug>"
echo ""
echo "      4. gh pr create \\"
echo "         --base ${BRANCH} --head feat/<chain-id>-<slug> \\"
echo "         --title \"feat(<chain-id>): <titles>\" \\"
echo "         --body \"Chain: <phase-list>"
echo "         Plan: ${PLAN_FILE}"
echo "         Phases implemented sequentially in one branch.\""
echo ""
echo "      5. Report EXACTLY:"
echo "         STATUS: SUCCESS | FAILURE"
echo "         BRANCH: feat/<chain-id>-<slug>"
echo "         PR: <pr-url>"
echo "         PHASES:"
echo "           - <phase-id>: PASS|FAIL"
echo "         FILES:"
echo "           - <absolute-path>"
echo ""

echo "=== auto-implement-and-pr v6.2 END ==="
