#!/usr/bin/env bash
# ============================================================================
# auto-plan-implement-and-pr.sh — v5.1 (DAG-driven, program-logic deps)
# Claude Code instruction document: reads design docs, generates a plan,
# AUTO-DETECTS dependencies from PROGRAM DEVELOPMENT LOGIC (creates->consumes)
# AND enforces HARD file-overlap constraint (no same-file parallel edits),
# dispatches wave-by-wave, then PR.
#
# USAGE:  cat auto-plan-implement-and-pr.sh | claude
#    OR   open this file in Claude Code and say "run this script"
# ============================================================================

# ======================= Configuration =======================
EXTERNAL_DESIGN_DIR="d:/ewm robot/reference/design all"
IMPL_PLAN_DIR="${EXTERNAL_DESIGN_DIR}/implementation plan"
PROJECT_ROOT="D:/EWM ROBOT/ROBOTIC PLATFORM CODES"
TODAY_DATE=$(date +%Y%m%d 2>/dev/null || echo 'TODAY')
PLAN_FILE=$(ls -t "${IMPL_PLAN_DIR}"/*${TODAY_DATE}*.* 2>/dev/null | head -1)
if [ -z "${PLAN_FILE}" ]; then
  PLAN_FILE="${IMPL_PLAN_DIR}/IMPLEMENTATION_PLAN_${TODAY_DATE}.md"
fi
BRANCH_NAME="feat/auto-impl-$(date +%Y%m%d-%H%M%S 2>/dev/null || echo 'snapshot')"
# ============================================================

echo "=============================================="
echo " auto-plan-implement-and-pr.sh v5.1 (DAG-driven)"
echo " Design dir : ${EXTERNAL_DESIGN_DIR}"
echo " Plan file  : ${PLAN_FILE}"
echo " Root       : ${PROJECT_ROOT}"
echo "=============================================="
echo ""

# ╔══════════════════════════════════════════════════════════════╗
# ║  CRITICAL RULE — READ THIS FIRST                           ║
# ╚══════════════════════════════════════════════════════════════╝
#
# YOU (Claude Code) are the ORCHESTRATOR, not the implementer.
# Your job has 3 stages:
#   STAGE 1: Read design docs + explore codebase -> write a plan file.
#            Each phase declares PRIORITY (P0/P1), CREATES, CONSUMES, FILES.
#            The plan does NOT declare dependencies.
#   STAGE 2: Auto-detect constraints from TWO layers:
#            Layer 1 (LOGICAL): creates->consumes matching.
#            Layer 2 (MECHANICAL): same file = cannot run in parallel.
#            Dispatch wave-by-wave. Use Agent tool. Do NOT edit code.
#   STAGE 3: PR decision based on priority: P0 failed -> no PR.
#
# v5.1 KEY PRINCIPLES:
#
#   PRIORITY (P0/P1) = how critical this phase is. Like severity.
#     Declared by the plan author. Affects dispatch order (P0 first)
#     and PR decision (P0 failure = no PR). NOT a dependency.
#
#   LOGICAL DEPENDENCY = does B USE what A CREATES?
#     Auto-detected by matching CREATES -> CONSUMES across phases.
#     Based on program development logic, not file overlap.
#     Example: P1-4 creates GET /playback, P1-6 calls it -> dependency.
#
#   MECHANICAL CONSTRAINT = same file = CANNOT run in parallel.
#     HARD rule. Even different lines in the same file -> must sequence.
#     Two agents editing config.py simultaneously -> git conflict.
#     File overlap ALWAYS forces sequencing. No exceptions.

echo "=== STAGE 1/3: ANALYSIS & PLAN GENERATION ==="
echo ""

# ═══════════════════════════════════════════════════════════════
# STAGE 1 — READ DOCS + CODEBASE -> WRITE PLAN
# ═══════════════════════════════════════════════════════════════
echo "STEP 1A — Read external design documents"
echo ""
echo "   Use Glob + Read to find and read ALL .md files in:"
echo "     - ${IMPL_PLAN_DIR}/"
echo "     - ${EXTERNAL_DESIGN_DIR}/Design - Core/"
echo ""
echo "   Plan file discovery:"
echo "     Go to folder: ${IMPL_PLAN_DIR}"
echo "     Find the file whose name contains today's date: ${TODAY_DATE}"
echo "     If multiple match, pick the most recently modified one."
echo "     If one exists already: ${PLAN_FILE}"
echo ""
echo "   Key documents (read these FIRST):"
echo "     - The plan file with today's date in ${IMPL_PLAN_DIR}/"
echo "     - 异构机器人融合平台_v5.0_完整堡垒版.md (integration master)"
echo "     - 01_架构白皮书_v5.0.md (architecture whitepaper)"
echo "     - 02_Function_Spec_v5.0.md (function spec with interfaces)"
echo "     - 03_Runbook_v5.0.md (SOP cards, Grafana charts, alerting)"
echo ""

echo "STEP 1B — Explore current codebase"
echo ""
echo "   Use Glob to list ${PROJECT_ROOT} top-level directory."
echo "   Read these key files to understand current patterns:"
echo "     core/config.py          — CoreConfig dataclass (central config)"
echo "     core/coordinator.py     — RobotPlatformCoordinator (integration heart)"
echo "     core/gateway.py         — MQTT gateway (transport layer)"
echo "     core/survival/worm_blackbox.py  — WORM audit ledger"
echo "     core/survival/version_router.py — N-1 compatibility"
echo "     traffic_coordinator_v5/traffic_coordinator_main.py — main service"
echo "     traffic_coordinator_v5/simulator/cli.py  — simulator CLI"
echo "     traffic_coordinator_v5/simulator/fleet.py — fleet manager"
echo "     docker-compose-v5.yml   — Docker Compose v5 stack"
echo "     core/tests/test_platform_adapter_survival.py — existing tests"
echo "     core/tests/test_vda5050_adapters.py — VDA5050 tests"
echo "     dashboard/src/          — React dashboard (list structure)"
echo "     monitoring/             — Prometheus/Grafana configs"
echo ""

echo "STEP 1C — Analyze program logic + file overlap BEFORE writing phases"
echo ""
echo "   ============================================================"
echo "   For each candidate phase, determine:"
echo "   ============================================================"
echo ""
echo "   Q1: What does this phase CREATE?"
echo "       -> New functions/methods added to existing modules"
echo "       -> New classes"
echo "       -> New API endpoints (GET/POST /path)"
echo "       -> New config keys/fields in dataclasses"
echo "       -> New files/modules"
echo "       -> New CLI flags"
echo "       -> New Docker volumes, services, or configs"
echo ""
echo "   Q2: What does this phase CONSUME?"
echo "       -> Imports from other modules"
echo "       -> Function/method calls on existing (or to-be-created) code"
echo "       -> API endpoint calls"
echo "       -> Config key reads"
echo "       -> CLI argument parsing"
echo ""
echo "   Q3: Which FILES does this phase touch?"
echo "       -> *** CRITICAL: phases touching the SAME FILE cannot run in parallel ***"
echo "       -> Even if they modify different functions/lines."
echo "       -> File overlap ALWAYS forces sequencing."
echo "       -> If a file has many phases touching it, split the phase or"
echo "         merge related changes to reduce contention."
echo ""
echo "   Example analysis:"
echo ""
echo "     P0-1 (Cold Start Stagger):"
echo "       CREATES:  registration_stagger_seconds in CoreConfig,"
echo "                 _pending_registrations deque, stagger logic"
echo "       CONSUMES: CoreConfig (existing), Coordinator.ingest_uplink(), tick()"
echo "       FILES:    core/config.py, core/coordinator.py, core/tests/test_...survival.py"
echo ""
echo "     P0-2 (DEMO/PROD Mode):"
echo "       CREATES:  CoreConfig.for_demo(), DEMO/PROD branches,"
echo "                 WORM in-memory fallback"
echo "       CONSUMES: CoreConfig (existing), Coordinator, WORM worm_blackbox"
echo "       FILES:    core/config.py, core/coordinator.py, core/.../worm_blackbox.py,"
echo "                 traffic_coordinator_v5/.../main.py, core/tests/test_...survival.py"
echo ""
echo "     -> P0-1 and P0-2 SHARE files: config.py, coordinator.py, test_survival.py"
echo "     -> MECHANICAL CONSTRAINT: they CANNOT run in parallel."
echo "     -> Must be sequenced. P0-1 before P0-2 (lower ID, same priority)."
echo "     -> Even though neither consumes what the other creates,"
echo "        they still cannot run together because of shared files."
echo ""
echo "     P1-4 (Playback API):"
echo "       CREATES:  GET /playback, worm_blackbox.replay_recent()"
echo "       CONSUMES: worm_blackbox, traffic_coordinator_main"
echo "       FILES:    traffic_coordinator_v5/.../main.py, core/.../worm_blackbox.py,"
echo "                 core/tests/test_vda5050_adapters.py"
echo ""
echo "     P1-6 (Dashboard v5):"
echo "       CREATES:  PlaybackPanel, 1s polling hook"
echo "       CONSUMES: /v1/v5/state, /v1/v5/playback, v5 robot state"
echo "       FILES:    dashboard/src/hooks/usePlatformState.ts,"
echo "                 dashboard/src/components/*.tsx (5 files)"
echo ""
echo "     -> P1-6 CONSUMES GET /playback. P1-4 CREATES GET /playback."
echo "     -> LOGICAL DEPENDENCY: P1-6 depends on P1-4."
echo "     -> Also: no shared files between P1-6 and P1-4 (dashboard vs backend)."
echo "        So only the logical dep matters here."
echo ""

echo "STEP 1D — Write implementation plan to ${PLAN_FILE}"
echo ""
echo "   DERIVE phases from design docs. Do NOT use a fixed list."
echo "   The plan MUST include these sections:"
echo ""
echo "   ## 1. CURRENT BASELINE"
echo "     - What exists, test counts, known gaps, recent git activity"
echo ""
echo "   ## 2. IMPLEMENTATION PHASES"
echo "     For EACH phase, this EXACT template:"
echo ""
echo "     --------------------------------------------------------"
echo "     ### <Phase ID>: <Title>"
echo ""
echo "     **Priority:** P0 | P1"
echo "       P0 = critical. Failure blocks PR. Runs first when tied."
echo "       P1 = normal.   Failure noted in PR. Runs after P0 if tied."
echo "       This is ONLY a criticality label. NOT a dependency."
echo ""
echo "     **Creates:**"
echo "       - \`function_name()\` in \`module.py\` — new method"
echo "       - \`GET /api/endpoint\` in \`main.py\` — new REST route"
echo "       - \`ConfigKey.field\` in \`config.py\` — new config field"
echo "       Every new artifact this phase PRODUCES."
echo "       Used by orchestrator to detect who logically depends on YOU."
echo ""
echo "     **Consumes:**"
echo "       - \`existing_func()\` from \`module.py\` — existing code"
echo "       - \`GET /api/existing\` — existing endpoint"
echo "       - \`CoreConfig.existing_field\` — existing config"
echo "       Every artifact this phase USES (existing or to-be-created)."
echo "       If you consume something another phase CREATES, the"
echo "       orchestrator auto-detects the logical dependency."
echo ""
echo "     **Files:**"
echo "       - \`path/to/file\` — what to change"
echo "       Be EXHAUSTIVE. Every file touched must be listed."
echo "       *** Phases sharing files CANNOT run in parallel. ***"
echo "       If a file appears in many phases, consider splitting or"
echo "       merging phases to reduce contention."
echo ""
echo "     **Changes:**"
echo "       - Specific implementation details"
echo ""
echo "     **Verify:** \`exact command to run\`"
echo "     --------------------------------------------------------"
echo ""
echo "     *** DO NOT add a **Depends on:** field. ***"
echo "     Dependencies are auto-detected by the orchestrator from:"
echo "       1. Creates->Consumes matching (logical dependency)"
echo "       2. File overlap (mechanical constraint)"
echo "     The plan author only declares what each phase CREATES,"
echo "     CONSUMES, and which FILES it touches."
echo ""
echo "   ## 3. CREATES/CONSUMES CROSS-REFERENCE (for review)"
echo "     Table: Phase | Creates | Consumes | Files"
echo "     Auto-derived. Helps verify correctness."
echo ""
echo "   ## 4. FILE CONTENTION MAP (for review)"
echo "     Table: File | Phases | Contention Level"
echo "     Identifies bottleneck files. High contention -> consider"
echo "     merging phases or splitting files."
echo ""
echo "   ## 5. VERIFICATION CRITERIA"
echo "     Per-phase test commands + global regression: pytest -q"
echo ""
echo "   ## 6. FILE CHANGE MATRIX"
echo "     Table: path | new/modified | phase | change summary"
echo ""
echo "   ## 7. OUT OF SCOPE"
echo "     Explicitly excluded items"
echo ""
echo "   After writing, confirm the file exists and report its path + line count."
echo ""

# ═══════════════════════════════════════════════════════════════
# BRANCH CREATION — BEFORE ANY CODE CHANGES
# ═══════════════════════════════════════════════════════════════
echo "CREATE FEATURE BRANCH BEFORE STAGE 2"
echo ""
echo "   ACTION: Run these git commands BEFORE dispatching any agent:"
echo "     1. cd ${PROJECT_ROOT}"
echo "     2. git status                    # review starting state"
echo "     3. git checkout -b ${BRANCH_NAME}  # create and switch"
echo "     4. git branch --show-current      # confirm"
echo ""
echo "   WHY: All subagent changes land on this branch from the start."
echo "   If branch already exists, use 'git checkout ${BRANCH_NAME}' instead."
echo "   If there are uncommitted changes, stash them first: git stash"
echo ""
echo "   *** Do NOT proceed to Stage 2 until branch is confirmed. ***"
echo ""

# ═══════════════════════════════════════════════════════════════
# STAGE 2 — AUTO-DETECT CONSTRAINTS + DISPATCH WAVE BY WAVE
# ═══════════════════════════════════════════════════════════════
echo "==========================================================="
echo "  STAGE 2/3: AUTO-DETECT + DAG DISPATCH"
echo "==========================================================="
echo ""
echo "CRITICAL: Use the Agent tool for EVERY phase. Do NOT implement code yourself."
echo ""

echo "STEP 2A — Auto-detect constraints (TWO LAYERS)"
echo ""
echo "   Read ${PLAN_FILE}."
echo "   For EVERY phase, extract: id, title, priority, creates, consumes, files, verify."
echo ""

echo "   LAYER 1 — LOGICAL dependencies (creates -> consumes):"
echo ""
echo "   1. Build lookup tables:"
echo "        creates_map[artifact_key] = [phase_ids that CREATE it]"
echo "        consumes_map[artifact_key] = [phase_ids that CONSUME it]"
echo ""
echo "      Artifact key format:"
echo "        function:  \"module.py::function_name()\""
echo "        class:     \"module.py::ClassName\""
echo "        endpoint:  \"GET /api/path\" or \"POST /api/path\""
echo "        config:    \"ClassName.field_name\""
echo "        file:      \"path/to/file.py\" (only for NEW files)"
echo "        cli:       \"cli.py::--flag-name\""
echo ""
echo "   2. Match: For each artifact in creates_map:"
echo "        producers = creates_map[key]"
echo "        consumers = consumes_map[key]"
echo "        For each (producer, consumer) where producer != consumer:"
echo "          consumer LOGICALLY depends on producer"
echo ""

echo "   LAYER 2 — MECHANICAL constraints (same file = cannot parallel):"
echo ""
echo "   *** IRON RULE: Two agents MUST NOT edit the SAME FILE simultaneously. ***"
echo ""
echo "   3. Build file->phases map:"
echo "        file_map[path] = [phase_ids that list this file]"
echo ""
echo "   4. For each file touched by >1 phase:"
echo "        These phases CONFLICT mechanically -> must be sequenced."
echo "        Order: P0 before P1, then by phase ID."
echo ""

echo "   COMBINED DAG:"
echo ""
echo "   5. For each phase, FULL deps ="
echo "        (logical deps from Layer 1) UNION (mechanical deps from Layer 2)"
echo ""
echo "   6. Print the combined DAG:"
echo ""
echo "     Phase     | Prio | Logical Deps    | File Conflicts      | FULL Deps"
echo "     ----------|------|-----------------|---------------------|----------"
echo "     P0-1: ... | P0   | (none)          | (none)              | (none)"
echo "     P0-2: ... | P0   | (none)          | P0-1(config.py,...) | P0-1"
echo "     P0-3: ... | P0   | (none)          | P0-2(config.py)     | P0-2"
echo "     P1-4: ... | P1   | (none)          | P0-2(main.py,...)   | P0-2"
echo "     P1-5: ... | P1   | (none)          | P0-2,P1-4(main.py)  | P0-2,P1-4"
echo "     P1-6: ... | P1   | P1-4(/playback) | (none)              | P1-4"
echo "     P1-7: ... | P1   | (none)          | (none)              | (none)"
echo "     P1-8: ... | P1   | (none)          | (none)              | (none)"
echo ""

echo "STEP 2B — Dispatch wave by wave"
echo ""
echo "   WAVE 1: Phases with EMPTY full-deps list."
echo "     *** ALSO check: no shared files among Wave 1 candidates. ***"
echo "     If two candidates share a file, only dispatch the highest-priority one."
echo ""
echo "   WAVE 2+: Re-evaluate after each wave completes."
echo "     Which pending phases have all deps satisfied?"
echo "     AND do not share files with any other ready phase?"
echo "     -> Dispatch in parallel."
echo ""
echo "   FAILURE: Any phase fails -> dependents cascade-skip."
echo "     Unrelated phases continue. P0/P1 only differ at PR time."
echo ""
echo "   STOP: When no phases remain pending or in_progress."
echo ""

echo "   AGENT PROMPT (identical for all phases):"
echo ""
echo "     subagent_type: \"general-purpose\""
echo "     description: \"<Phase ID> [<P0|P1>]: <title>\""
echo "     prompt: |"
echo "       Implement one phase from the plan at: ${PLAN_FILE}"
echo "       Project root: ${PROJECT_ROOT}"
echo "       Your phase: <Phase ID> [Priority: <P0|P1>] - <Title>"
echo ""
echo "       1. Read YOUR phase section from the plan."
echo "       2. Read EVERY file listed BEFORE editing."
echo "       3. Make ALL changes described. Match existing code style."
echo "       4. Run verification command. Fix until green."
echo "       5. Report: SUCCESS + output, or FAILURE + errors."
echo "          List every file you modified."
echo ""

# ═══════════════════════════════════════════════════════════════
# STAGE 3 — GIT + PR
# ═══════════════════════════════════════════════════════════════
echo "==========================================================="
echo "  STAGE 3/3: GIT + PR WORKFLOW"
echo "==========================================================="
echo ""
echo "After all waves complete."
echo ""
echo "  1. cd ${PROJECT_ROOT}"
echo "  2. git status          # review all changes on ${BRANCH_NAME}"
echo "  3. git add .           # (branch already created before Stage 2)"
echo "  4. git commit -m \"feat: auto-implemented from design docs ($(date +%Y%m%d))"
echo ""
echo "     <per-phase: [PASS|FAIL|SKIP] <id> [<P0|P1>]: <title>>\""
echo ""
echo "  5. git push -u origin ${BRANCH_NAME}"
echo ""
echo "  6. PR DECISION (based on PRIORITY, not dependency):"
echo "     -> Any P0 phase failed? -> STOP. No PR (critical path broken)."
echo "     -> Only P1 failed (or all pass)? -> Create PR:"
echo ""
echo "     gh pr create \\"
echo "       --title \"feat: auto-implemented ($(date +%Y%m%d))\" \\"
echo "       --body \"Generated with Claude Code auto-plan-implement-and-pr.sh v5.1"
echo ""
echo "  Plan: ${PLAN_FILE}"
echo "  Branch: ${BRANCH_NAME}"
echo "  Constraints: logical (creates->consumes) + mechanical (file overlap)"
echo ""
echo "  Results:"
echo "  <per-phase: [PASS|FAIL|SKIP] <id> [<P0|P1>]: <title>>"
echo ""
echo "  Summary: <N> succeeded, <M> failed, <K> skipped\""
echo "  7. Output the PR URL"
echo ""

echo "=============================================="
echo " auto-plan-implement-and-pr.sh v5.1 — END"
echo "=============================================="
